import { Inter } from "next/font/google";
import "../styles/core/globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Main from "@/components/layout/Main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PokeNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pr-BR">
      <body className={inter.className}>
        <Navbar />
        <Main>
          {children}
        </Main>
        <Footer />
      </body>
    </html>
  );
}
